### ISSUE TITLE
modify the login endpoint to take a file (image)

### ISSUE THREAD

**Issue by techieeliot** [leviking/KikiSaver#28]

**Comment by localpathcomp** [comment]
we want to just save a url right? we need to save the actual image in a directory in our project? then we write an express route that serves up dynamically any file requested in that directory?

**Comment by techieeliot** [comment]
@localpathcomp are y'all working on this issue? Go ahead and assign yourselves, if you are.

**Comment by techieeliot** [comment]
closed by #109
