### ISSUE TITLE
Add link to login page on signup page

### ISSUE THREAD

**Issue by techieeliot** [leviking/KikiSaver#54]
say something like this:

```html
<p>Already signed up. <a href="/signup">Login!</a></p>
```

**Comment by yonis9** [comment]
@techieeliot Hi, can I take it?

**Comment by techieeliot** [comment]
@yonis9 thanks for asking, but this project is designated as an assignment for our coding bootcamp. Also, I created this one for a specific teammate. Awaiting his acceptance to collaborate with him later today. 

Feel free to follow me. I'll likely make this sort of assignment again and would be willing to collab on my own repos, especially for freeCodeCamp Jackson, MS.

**Comment by yonis9** [comment]
OK, no problem.
