### ISSUE TITLE
display html file with username & timestamp for attendance

### ISSUE THREAD

**Issue by techieeliot** [leviking/KikiSaver#55]
The output will send a view/success.html when login succeeds.

Including: 
- same text
- timestamp
- username

![Screen Shot 2020-03-19 at 7 34 01 AM](https://user-images.githubusercontent.com/19453294/77068272-4d4ad100-69b4-11ea-8233-c89094cf3ab0.png)

![Screen Shot 2020-03-19 at 7 30 35 AM](https://user-images.githubusercontent.com/19453294/77067886-aa925280-69b3-11ea-9600-a1120956a2d6.png)

**Comment by jnelson1988** [comment]
I'm going to work on this one. I'll assign later
